[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ "ferris", "protocol"]

[dependencies]
protocol = { path = "./protocol" }
ferris = { path = "./ferris" }
serde_json = "1.0.140"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
